stages:
  - build
  - integration

compile:
  stage: build
  tags:
    - arch
  image: epitechcontent/epitest-docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - git submodule update --init
  script:
    - cmake -S . -B build
    - cd build
    - make -j12
