stages:
  - build

default:
  image: epitechcontent/epitest-docker

compile:
  stage: build
  tags:
    - arch
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - git submodule update --init
    #script:
    #- cmake -S . -B build
    #- cd build
    #- make -j12
