[project]
name = "zappy_ai"
requires-python = ">= 3.8"
version = "0.1.0"

[project.scripts]
zappy_ai = "zappy_ai:main_cli"

[tool.setuptools]
py-modules = [
    "args_handling",
    "client",
    "parser",
    "trentorian",
    "utils",
    "zappy_ai",
]
